name = "studybuddy-worker"
main = "worker.js"
compatibility_date = "2023-10-25"

# Configure environment variables for storing API keys
# In development, add your keys here
# For production, use the Cloudflare dashboard to set these securely
[vars]
# Add your API keys here (for development only)
# GROQ_API_KEY_1 = "your_groq_key_1"
# GROQ_API_KEY_2 = "your_groq_key_2"
# GEMINI_API_KEY_1 = "your_gemini_key_1"
# GEMINI_API_KEY_2 = "your_gemini_key_2"
# TAVILY_API_KEY_1 = "your_tavily_key_1"
# TAVILY_API_KEY_2 = "your_tavily_key_2"